gems:
  - jekyll-feed

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: post

name: Curtis McEnroe
email: curtis@cmcenroe.me
url: https://cmcenroe.me
domain: cmcenroe.me

nav:
  pages:
    - name: Home
      href: /

    - name: Projects
      href: /projects.html

    #- name: Résumé
    #- href: /resume.html

  links:
    - name: GitHub
      href: https://github.com/programble
      icon: fa-github-alt

    - name: Email
      href: mailto:curtis@cmcenroe.me
      icon: fa-envelope

    - name: Key
      href: http://pgp.mit.edu/pks/lookup?op=get&search=0xCEA2F97ADCFCD77C
      icon: fa-lock
