markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - strikethrough
    - superscript
    - tables
    - with_toc_data
gems:
  - jekyll-feed
  - jemoji

name: Curtis McEnroe
email: curtis@cmcenroe.me
domain: cmcenroe.me
gravatar: ca0c9cb798fd7f80444740a4dbaef7b9

nav:
  pages:
    - name: Home
      href: /

    - name: Projects
      href: /projects.html

    - name: Résumé
      href: /resume.html

  links:
    - name: GitHub
      href: https://github.com/programble
      icon: fa-github-alt

    - name: LinkedIn
      href: https://ca.linkedin.com/in/cmcenroe
      icon: fa-linkedin

    - name: Email
      href: mailto:curtis@cmcenroe.me
      icon: fa-envelope

    - name: Keybase
      href: https://keybase.io/programble
      icon: fa-lock
