gems:
  - jekyll-feed

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: post

name: Curtis McEnroe
email: curtis@causal.agency
url: https://cmcenroe.me
domain: cmcenroe.me

nav:
  - name: Posts
    href: /

  - name: Résumé
    href: /resume.html

  - name: Projects
    href: https://github.com/programble

  - name: Email
    href: mailto:curtis@causal.agency

  - name: Key
    href: http://pgp.mit.edu/pks/lookup?op=get&search=0xCEA2F97ADCFCD77C
