kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-feed
url: https://cmcenroe.me

name: C. McEnroe
domain: cmcenroe.me
email: june@causal.agency
github: causal-agent

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: post
