kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-feed
url: https://cmcenroe.me

name: Curtis McEnroe
domain: cmcenroe.me
email: curtis@causal.agency
key: 0xCEA2F97ADCFCD77C
github: programble

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: post
